import os

ELK_URL = os.environ["ELK_URL"]
ELK_PASSWORD = os.environ["ELK_PASSWORD"]
ELK_USERNAME = os.environ["ELK_USERNAME"]
ELK_REMOTE_IP = os.environ["ELK_REMOTE_IP"]

ELASTICSEARCH_MAX_TIMEOUT_IN_SECONDS = 500
INDEX_DATE_FMT = "%Y-%m-%d"
MAX_CHUNK_SIZE_IN_BYTES = 100000000000  # 100MB
INGEST_DATA_MAXIMUM_RETRIES = 5
INGEST_DATA_INIT_BACKOFF = 2
INGEST_DATA_MAX_BACKOFF = 30
CHUNK_SIZE = 500
